### ISSUE TITLE
Add force-stop mode

### ISSUE THREAD

**Issue by dberzano** [mconcas/plancton#85]
Just like `stop` but kills all pertaining containers first.

**Comment by mconcas** [comment]
It might look trivial to implement, actually it is not. 
Basically this is because when we run a `planctonctl` command we are not using the same `plancton` instance running in background.
As you know better than me, we stop the daemon by sending `SIGTERM/SIGKILL` to the proper process, and that's why giving `planctonctl stop` does the job. 
At the moment I am considering two possible solutions to realise the `force-kill` behaviour:

1. Use a custom `POSIX` signal to trigger the deletion of all containers
2. Set the daemon in `drain mode`, wait for an entire loop and the force-kill all containers. This is necessary, because it may happen that containers are killed during the spawning phase, creating inconsistency both for the daemon and for the `force-kill` command, since two plancton instances are _de-facto_ independent.

After further considerations I am currently not sure that the second option can even be adopted safely.

**Comment by mconcas** [comment]
Third option: create another _placeholder_ to tell `plancton` to kill containers.

**Comment by dberzano** [comment]
Third option :+1:
